version: '3.7'
services:
  webserver:
    image: nginx:1.17
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infrastructure/nginx:/etc/nginx/conf.d/
      - ./arquivei:/app
    depends_on:
      - php-fpm
      - db

  php-fpm:
    image: php-fpm
    build: .
    ports:
      - '9000'
    volumes:
      - ./arquivei:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  artisan:
    image: php-fpm
    command: php artisan migrate
    volumes:
      - ./arquivei:/app
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  composer:
    image: composer
    command: composer install
    volumes:
      - ./arquivei:/app
    environment:
      - COMPOSER_HOME=${COMPOSER_HOME}

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
